// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plc} from '../models';
import {backend} from '../models';

export function AddWatchedTag(arg1:plc.WatchedTag):Promise<void>;

export function Connect(arg1:plc.ConnectionConfig):Promise<void>;

export function Disconnect():Promise<void>;

export function DiscoverTags():Promise<Array<plc.DiscoveredTag>>;

export function ExportWatchedTags(arg1:string):Promise<string>;

export function GetConnectionStatus():Promise<plc.ConnectionStatus>;

export function GetWatchedTags():Promise<Array<plc.WatchedTag>>;

export function ImportWatchedTags(arg1:Array<plc.WatchedTag>):Promise<backend.WatchListImportResult>;

export function ReadTag(arg1:plc.WatchedTag):Promise<plc.TagSnapshot>;

export function RemoveWatchedTag(arg1:string):Promise<void>;

export function SetPollInterval(arg1:number):Promise<void>;

export function StartPolling():Promise<void>;

export function StopPolling():Promise<void>;

export function UpdateWatchedTag(arg1:plc.WatchedTag):Promise<void>;

export function WriteTag(arg1:plc.WriteRequest):Promise<plc.WriteResult>;
