// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWatchedTag(arg1) {
  return window['go']['backend']['App']['AddWatchedTag'](arg1);
}

export function Connect(arg1) {
  return window['go']['backend']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['backend']['App']['Disconnect']();
}

export function DiscoverTags() {
  return window['go']['backend']['App']['DiscoverTags']();
}

export function GetConnectionStatus() {
  return window['go']['backend']['App']['GetConnectionStatus']();
}

export function GetWatchedTags() {
  return window['go']['backend']['App']['GetWatchedTags']();
}

export function ReadTag(arg1) {
  return window['go']['backend']['App']['ReadTag'](arg1);
}

export function RemoveWatchedTag(arg1) {
  return window['go']['backend']['App']['RemoveWatchedTag'](arg1);
}

export function SetPollInterval(arg1) {
  return window['go']['backend']['App']['SetPollInterval'](arg1);
}

export function StartPolling() {
  return window['go']['backend']['App']['StartPolling']();
}

export function StopPolling() {
  return window['go']['backend']['App']['StopPolling']();
}

export function UpdateWatchedTag(arg1) {
  return window['go']['backend']['App']['UpdateWatchedTag'](arg1);
}

export function WriteTag(arg1) {
  return window['go']['backend']['App']['WriteTag'](arg1);
}
